<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('items', function (Blueprint $table) {
            $table->id('ins_idno');
            $table->string('ins_name', 50);
            $table->string('ins_type', 50);
            $table->string('datereleased', 20);
            $table->string('ins_model', 50);
            $table->string('brand', 50);
            $table->string('price', 20);
            $table->text('img');
            $table->string('status', 20)->default('Available');
            $table->timestamps();
        });

        DB::table('items')->insert([
            [
                'ins_idno' => 13569,
                'ins_name' => 'Piano',
                'ins_type' => 'String',
                'datereleased' => '2019',
                'ins_model' => 'b1 SG2',
                'brand' => 'Yamaha',
                'price' => '₱40,000',
                'img' => '13569.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13570,
                'ins_name' => 'Flute',
                'ins_type' => 'Wind',
                'datereleased' => '2020',
                'ins_model' => 'YFL-211SL',
                'brand' => 'Yamaha',
                'price' => '₱5,599',
                'img' => '13570.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13571,
                'ins_name' => 'Snare Drum',
                'ins_type' => 'Percussion',
                'datereleased' => '2021',
                'ins_model' => 'MUS1270',
                'brand' => 'Pearl',
                'price' => '₱7,739',
                'img' => '13571.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13572,
                'ins_name' => 'Electric Guitar',
                'ins_type' => 'String',
                'datereleased' => '2019',
                'ins_model' => '60S Pau Ferro Telecaster',
                'brand' => 'Fender',
                'price' => '₱18,910',
                'img' => '13572.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13573,
                'ins_name' => 'Junior Drum Set',
                'ins_type' => 'Percussion',
                'datereleased' => '2019',
                'ins_model' => 'JBJ1045',
                'brand' => 'Fernando',
                'price' => '₱28,890',
                'img' => '13573.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13574,
                'ins_name' => 'Violin',
                'ins_type' => 'String',
                'datereleased' => '2022',
                'ins_model' => 'OV-100',
                'brand' => 'Fernando',
                'price' => '₱4,400',
                'img' => '13574.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13575,
                'ins_name' => 'Keyboard',
                'ins_type' => 'Percussion',
                'datereleased' => '2022',
                'ins_model' => 'CODE61BK',
                'brand' => 'M-Audio',
                'price' => '₱24,800',
                'img' => '13575.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13576,
                'ins_name' => 'Saxophone',
                'ins_type' => 'Wind',
                'datereleased' => '2019',
                'ins_model' => 'AL-107B',
                'brand' => 'Fernando',
                'price' => '₱25,400',
                'img' => '13576.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13577,
                'ins_name' => 'Harmonica',
                'ins_type' => 'Wind',
                'datereleased' => '2019',
                'ins_model' => '10H C',
                'brand' => 'Overdrive',
                'price' => '₱2,080',
                'img' => '13577.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13578,
                'ins_name' => 'Cymbal',
                'ins_type' => 'Percussion',
                'datereleased' => '2020',
                'ins_model' => 'ZBT22R',
                'brand' => 'Zildjian',
                'price' => '₱5,700',
                'img' => '13578.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13579,
                'ins_name' => 'Keyboard',
                'ins_type' => 'Percussion',
                'datereleased' => '2022',
                'ins_model' => 'Arturita 61',
                'brand' => 'Keylab Essential',
                'price' => '₱18,900',
                'img' => '13579.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13580,
                'ins_name' => 'Acoustic Guitar',
                'ins_type' => 'String',
                'datereleased' => '2021',
                'ins_model' => 'TF Baby',
                'brand' => 'Fernando',
                'price' => '₱6,205',
                'img' => '13580.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13581,
                'ins_name' => 'Saxophone',
                'ins_type' => 'Wind',
                'datereleased' => '2021',
                'ins_model' => 'AASS-301',
                'brand' => 'Allora',
                'price' => '₱34,887',
                'img' => '13581.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13582,
                'ins_name' => 'Clarinet',
                'ins_type' => 'Wind',
                'datereleased' => '2022',
                'ins_model' => 'ECL-200',
                'brand' => 'Etude',
                'price' => '₱17,162',
                'img' => '13582.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13583,
                'ins_name' => 'Banduria',
                'ins_type' => 'String',
                'datereleased' => '2019',
                'ins_model' => 'CB-banduria11',
                'brand' => 'Ferangeli',
                'price' => '₱5,300',
                'img' => '13583.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13584,
                'ins_name' => 'Banduria',
                'ins_type' => 'String',
                'datereleased' => '2014',
                'ins_model' => 'CB-banduria14',
                'brand' => 'Ferangeli',
                'price' => '₱2,800',
                'img' => '13584.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13585,
                'ins_name' => 'Triangle',
                'ins_type' => 'Percussion',
                'datereleased' => '2022',
                'ins_model' => 'YFL-311TRG',
                'brand' => 'Pearl',
                'price' => '₱800',
                'img' => '13585.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13586,
                'ins_name' => 'Octavina',
                'ins_type' => 'String',
                'datereleased' => '2014',
                'ins_model' => 'OC-808',
                'brand' => 'Ferangeli',
                'price' => '₱12,890',
                'img' => '13586.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13587,
                'ins_name' => 'Trumpet',
                'ins_type' => 'Wind',
                'datereleased' => '2022',
                'ins_model' => '23B',
                'brand' => 'Conn',
                'price' => '₱37,500',
                'img' => '13587.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13588,
                'ins_name' => 'Harmonica',
                'ins_type' => 'Wind',
                'datereleased' => '2019',
                'ins_model' => 'N1072C',
                'brand' => 'Suzuki',
                'price' => '₱560',
                'img' => '13588.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13589,
                'ins_name' => 'Piano',
                'ins_type' => 'Percussion',
                'datereleased' => '2018',
                'ins_model' => 'CH190',
                'brand' => 'Fender',
                'price' => '₱290,000',
                'img' => '13589.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13590,
                'ins_name' => 'Flute',
                'ins_type' => 'Wind',
                'datereleased' => '2020',
                'ins_model' => 'FLUT678',
                'brand' => 'Pearl',
                'price' => '₱23,000',
                'img' => '13590.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13591,
                'ins_name' => 'Banduria',
                'ins_type' => 'String',
                'datereleased' => '2017',
                'ins_model' => 'MUS1332',
                'brand' => 'Orq',
                'price' => '₱2,800',
                'img' => '13591.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13592,
                'ins_name' => 'Snare Drum',
                'ins_type' => 'Percussion',
                'datereleased' => '2020',
                'ins_model' => 'SD009',
                'brand' => 'Fender',
                'price' => '₱5,000',
                'img' => '13592.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13593,
                'ins_name' => 'Keyboard',
                'ins_type' => 'Percussion',
                'datereleased' => '2021',
                'ins_model' => 'ROC9221',
                'brand' => 'Fernando',
                'price' => '₱25,000',
                'img' => '13593.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13594,
                'ins_name' => 'Harmonica',
                'ins_type' => 'Wind',
                'datereleased' => '2019',
                'ins_model' => 'WNDFL30',
                'brand' => 'Fender',
                'price' => '₱1,900',
                'img' => '13594.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13595,
                'ins_name' => 'Violin',
                'ins_type' => 'String',
                'datereleased' => '2021',
                'ins_model' => 'VLN6000',
                'brand' => 'UBEC',
                'price' => '₱5,800',
                'img' => '13595.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13596,
                'ins_name' => 'Cymbal',
                'ins_type' => 'Percussion',
                'datereleased' => '2020',
                'ins_model' => 'CBL445',
                'brand' => 'Fernando',
                'price' => '₱3,000',
                'img' => '13596.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13597,
                'ins_name' => 'Piano',
                'ins_type' => 'Percussion',
                'datereleased' => '2022',
                'ins_model' => 'PNO21',
                'brand' => 'Yamaha',
                'price' => '₱190,000',
                'img' => '13597.jpg',
                'status' => 'Available',
            ],
            [
                'ins_idno' => 13598,
                'ins_name' => 'Banduria',
                'ins_type' => 'String',
                'datereleased' => '2016',
                'ins_model' => 'BNDR222',
                'brand' => 'Orq',
                'price' => '₱2,490',
                'img' => '13598.jpg',
                'status' => 'Available',
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('items');
    }
};
